common:
    lid_topic: "/ouster/points"
    imu_topic: "/ouster/imu"
    time_offset_lidar_to_imu: 0.0

preprocess:
    lidar_type: 3                # 1: Livox, 2: Velodyne, 3: Ouster
    scan_line: 64
    timestamp_unit: 3            # 0: sec, 1: ms, 2: us, 3: ns
    blind: 1.0

mapping:
    acc_cov: 0.1
    gyr_cov: 0.1
    b_acc_cov: 0.0001
    b_gyr_cov: 0.0001
    fov_degree: 180
    det_range: 150.0
    extrinsic_est_en: false
    extrinsic_T: [ 0.0, 0.0, 0.0 ]
    extrinsic_R: [ 1.0, 0.0, 0.0,
                   0.0, 1.0, 0.0,
                   0.0, 0.0, 1.0 ]

max_iteration: 4
filter_size_surf: 0.5
filter_size_map: 0.5
cube_side_length: 200.0
point_filter_num: 2
feature_extract_enable: false
runtime_pos_log_enable: false
